-- CreateTable
CREATE TABLE "barbarreeee" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "isDead" BOOLEAN NOT NULL DEFAULT false,
    "born" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
